name: APCD CMS Builds
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apcd_cms/**"

jobs:
  build_commit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apcd_cms
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set shortsha and branch environment variables
        id: vars
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF_NAME} | sed 's/[^[:alnum:]\.\_\-]/-/g')" >> "$GITHUB_OUTPUT";
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT";

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push commit tagged Docker image
        uses: docker/build-push-action@v5
        with:
          context: apcd_cms
          push: true
          tags: taccwma/apcd-cms:${{ steps.vars.outputs.SHORT_SHA }},taccwma/apcd-cms:${{ steps.vars.outputs.BRANCH_NAME }}
